### ISSUE TITLE
Error resolving the running build's version number on non-default branch

### ISSUE THREAD

**Issue by chappoo** [BenPhegan/TeamCityBuildChanges#22]
Wanted to start a discussion prior to a pull request - not sure if this has been identified already.  Receiving the error below (sorry about formatting) when running TeamCityBuildChanges from a build off a branch called 'develop'.  

`Unhandled Exception: System.ApplicationException: Could not resolve a build number for the running build.
[22:26:33][Step 1/4]    at TeamCityBuildChanges.Commands.AggregateBuildDeltaResolver.ResolveToVersion(String buildType) in d:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Commands\AggregateBuildDeltaResolver.cs:line 198
[22:26:33][Step 1/4]    at TeamCityBuildChanges.Commands.AggregateBuildDeltaResolver.CreateChangeManifest(String buildName, String buildType, String referenceBuild, String from, String to, String projectName, Boolean useBuildSystemIssueResolution, Boolean recurse) in d:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Commands\AggregateBuildDeltaResolver.cs:line 88
[22:26:33][Step 1/4]    at TeamCityBuildChanges.Commands.AggregateBuildDeltaCommand.Run(String[] remainingArguments) in d:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Commands\AggregateBuildDeltaCommand.cs:line 37
[22:26:33][Step 1/4]    at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut) in c:\src\ManyConsole\ManyConsole\ConsoleCommandDispatcher.cs:line 70
[22:26:33][Step 1/4]    at TeamCityBuildChanges.Program.Main(String[] args) in d:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Program.cs:line 13
[22:26:42][Step 1/4] Process exited with code 255`

According to [the api documentation](http://confluence.jetbrains.com/display/TW/REST+API+Plugin#RESTAPIPlugin-BuildLocator) if no branch is specified in the build locator then only builds from the default branch are returned.

_branch:<branch locator> - since TeamCity 7.1 limit the builds by branch. <branch locator> can be branch name (displayed in UI, or "(name:<name>,default:<true/false/any>,unspecified:<true/false/any>,branched:<true/false/any>)". If not specified, only builds from default branch are returned._

Tempted just to use

```
branch:(default:any)
```

Interested in thoughts around the best solution prior to opening the code.

**Comment by chappoo** [comment]
Shall we close this one off?
