### ISSUE TITLE
AggregateBuildDeltaCommand throws an exception when querying a TeamCity build type that has not yet had a successful build

### ISSUE THREAD

**Issue by chappoo** [BenPhegan/TeamCityBuildChanges#24]
Exception logged below.  Suggested fix is to fall back to the version number of the running build (i.e. match the 'to' version for a default execution).

```
Unhandled Exception: System.ApplicationException: Could not find latest build for build type ?????????????
[17:44:53][Step 1/4]    at TeamCityBuildChanges.Commands.AggregateBuildDeltaResolver.ResolveFromVersion(String buildType, String branchName) in z:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Commands\AggregateBuildDeltaResolver.cs:line 215
[17:44:53][Step 1/4]    at TeamCityBuildChanges.Commands.AggregateBuildDeltaResolver.CreateChangeManifest(String buildName, String buildType, String referenceBuild, String from, String to, String projectName, Boolean useBuildSystemIssueResolution, Boolean recurse, String branchName) in z:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Commands\AggregateBuildDeltaResolver.cs:line 88
[17:44:53][Step 1/4]    at TeamCityBuildChanges.Commands.AggregateBuildDeltaCommand.Run(String[] remainingArguments) in z:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Commands\AggregateBuildDeltaCommand.cs:line 39
[17:44:53][Step 1/4]    at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut) in c:\src\ManyConsole\ManyConsole\ConsoleCommandDispatcher.cs:line 70
[17:44:53][Step 1/4]    at TeamCityBuildChanges.Program.Main(String[] args) in z:\Work\TeamCityBuildChanges\TeamCityBuildChanges\Program.cs:line 13
[17:45:29][Step 1/4] Process exited with code 255
```

**Comment by chappoo** [comment]
This can probably be closed??? 🤣
